#!/bin/bash

base=$(pwd)
plugin_dir="$base/plugin/"
control_dir="$plugin_dir/control"
app_dir="$base/app/"
pkg_dir="$base/pkg/"
app_port="4444"
log_dir="$base/log/"


set -u
set -e

. "$plugin_dir/functions"

create_app_skel
install_app
write_config
write_jvm_opts
write_system_props
write_control
